### ISSUE TITLE
get_timecourse ignores run-index

### ISSUE THREAD

**Issue by MichlF** [VU-Cog-Sci/response_fytter#9]
Right now GroupResponseFitter doesn't return time courses per run when I do grf.get_timecourses(). Instead, it gives the same output as get_subjectwise_timecourses, which it shouldn't.

**Comment by Gilles86** [comment]
OK, I looked into this. It turns out that `GroupResponseFitter` uses `concatenate_runs=True` by default. This means that all runs are concatenated in a single run and it's not possible to get run-wise estimates.

The solution is to set the `concatenate_runs`-argument to False when intializing `GroupResponseFitter`.
